#!/usr/bin/env python3
"""
MLB Video Pipeline - Main Entry Point

Usage:
    python main.py --date 2024-07-04 --team Yankees
    python main.py --date 2024-07-04 --team Yankees --cinematic
    python main.py --date 2024-07-04 --team Yankees --upload
    python main.py --watch --team Yankees
    python main.py --watch --team Yankees --cinematic
"""

import os
import sys
import logging
import argparse
from datetime import datetime, timedelta
from pathlib import Path
import PIL.Image

# Monkey-patch Pillow 10+ to fix MoviePy 'ANTIALIAS' error
if not hasattr(PIL.Image, 'ANTIALIAS'):
    PIL.Image.ANTIALIAS = PIL.Image.Resampling.LANCZOS

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

from src.pipeline import PipelineOrchestrator
from src.upload import YouTubeUploader

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler('logs/pipeline.log')
    ]
)

logger = logging.getLogger(__name__)


def watch(args):
    """Run the game watcher for real-time game detection."""
    from src.watcher import GameWatcher

    orchestrator = PipelineOrchestrator()

    def on_game_final(game):
        date = game.get("game_date", datetime.now().strftime("%Y-%m-%d"))
        # Use away or home team from the game data
        team = game.get("away_name", "") or game.get("home_name", args.team)

        if args.viral:
            video_path = orchestrator.run_viral_for_date(date, team)
        elif args.cinematic:
            video_path = orchestrator.run_cinematic_for_date(date, team)
        else:
            video_path = orchestrator.run_for_date(date, team)

        if video_path and args.upload and not args.dry_run:
            _upload_video(video_path, args, orchestrator, date, team)

    watcher = GameWatcher(
        teams=[args.team] if args.team else None,
        on_game_final=on_game_final,
    )

    logger.info("Starting game watcher... Press Ctrl+C to stop.")
    try:
        watcher.start()
    except KeyboardInterrupt:
        logger.info("Stopping game watcher...")
        watcher.stop()


def _upload_video(video_path, args, orchestrator, date, team):
    """Upload a generated video to YouTube."""
    try:
        uploader = YouTubeUploader()

        # Use script metadata from cinematic or viral mode if available
        script = getattr(orchestrator, "_last_cinematic_script", None) or \
                 getattr(orchestrator, "_last_viral_script", None)
        if (args.cinematic or args.viral) and script:
            metadata = script.get("video_metadata", {})
            title = metadata.get("title", f"MLB Recap: {team} - {date}")
            description = metadata.get("description", "")
            tags = metadata.get("tags", ["MLB", "Baseball", team, "MLB Shorts"])
        else:
            title = f"MLB Daily Recap: {team} - {date}"
            description = f"""
Daily MLB analysis and prediction for the {team}.

AI-Powered Predictions
Data-Driven Analysis
Professional Commentary

Generated by MLB Video Pipeline
            """.strip()
            tags = ["MLB", "Baseball", team, "Prediction", "Analysis"]

        video_id = uploader.upload_video(
            file_path=video_path,
            title=title,
            description=description,
            tags=tags,
            privacy_status="private",
        )

        if video_id:
            logger.info(f"Upload successful! Video ID: {video_id}")
        else:
            logger.warning("Upload failed, but video was generated successfully")

    except Exception as e:
        logger.error(f"Upload error: {e}")
        logger.info("Video was generated successfully despite upload failure")


def main():
    parser = argparse.ArgumentParser(
        description='MLB Video Pipeline - Automated video generation'
    )

    parser.add_argument(
        '--date',
        type=str,
        help='Date to process (YYYY-MM-DD). Defaults to yesterday.',
        default=None
    )

    parser.add_argument(
        '--team',
        type=str,
        help='Team name (e.g., Yankees, Red Sox)',
        default='Yankees'
    )

    parser.add_argument(
        '--upload',
        action='store_true',
        help='Upload video to YouTube after generation'
    )

    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Run without uploading (for testing)'
    )

    parser.add_argument(
        '--cinematic',
        action='store_true',
        help='Use cinematic video engine with AI images and Ken Burns effects'
    )

    parser.add_argument(
        '--watch',
        action='store_true',
        help='Watch for live game completions and auto-generate videos'
    )

    parser.add_argument(
        '--viral',
        action='store_true',
        help='Use viral pipeline with ESPN-style graphics and win probability model'
    )

    args = parser.parse_args()

    # Create necessary directories
    Path("logs").mkdir(exist_ok=True)
    Path("outputs/audio").mkdir(parents=True, exist_ok=True)
    Path("outputs/videos").mkdir(parents=True, exist_ok=True)
    Path("outputs/images").mkdir(parents=True, exist_ok=True)

    # Watch mode
    if args.watch:
        watch(args)
        return 0

    # Determine date
    if args.date:
        date = args.date
    else:
        yesterday = datetime.now() - timedelta(days=1)
        date = yesterday.strftime('%Y-%m-%d')

    if args.viral:
        mode = "viral"
    elif args.cinematic:
        mode = "cinematic"
    else:
        mode = "standard"

    logger.info("=" * 60)
    logger.info("MLB VIDEO PIPELINE")
    logger.info("=" * 60)
    logger.info(f"Date: {date}")
    logger.info(f"Team: {args.team}")
    logger.info(f"Mode: {mode}")
    logger.info(f"Upload: {args.upload and not args.dry_run}")
    logger.info("=" * 60)

    # Initialize and run pipeline
    try:
        orchestrator = PipelineOrchestrator()

        if args.viral:
            video_path = orchestrator.run_viral_for_date(date, args.team)
        elif args.cinematic:
            video_path = orchestrator.run_cinematic_for_date(date, args.team)
        else:
            video_path = orchestrator.run_for_date(date, args.team)

        if video_path:
            logger.info(f"SUCCESS! Video generated: {video_path}")

            if args.upload and not args.dry_run:
                logger.info("Uploading to YouTube...")
                _upload_video(video_path, args, orchestrator, date, args.team)

            return 0
        else:
            logger.error("FAILED: Video generation unsuccessful")
            return 1

    except Exception as e:
        logger.error(f"FATAL ERROR: {e}")
        import traceback
        traceback.print_exc()
        return 1

if __name__ == "__main__":
    sys.exit(main())
